# Generated by Django 4.1.4 on 2022-12-26 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0003_remove_createtodo_users_alter_userprofile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtodo',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='createtodo',
            name='todo',
            field=models.TextField(max_length=1000, verbose_name='Enter Todo'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
