# Generated by Django 4.1.4 on 2022-12-26 18:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0005_createtodo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createtodo',
            name='status',
        ),
    ]
