# Generated by Django 4.1.4 on 2022-12-26 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TodoApp', '0006_remove_createtodo_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='createtodo',
            name='status',
            field=models.CharField(choices=[('C', 'Completed'), ('P', 'Pending')], default=1, max_length=2),
            preserve_default=False,
        ),
    ]
